# Generated by Django 5.1.4 on 2025-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='product_picture')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='product_picture')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='product_picture')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='product_picture')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='product_picture')),
                ('description', models.TextField()),
                ('specification1', models.CharField(max_length=200)),
                ('specification2', models.CharField(max_length=200)),
                ('specification3', models.CharField(max_length=200)),
                ('specification4', models.CharField(max_length=200)),
                ('specification5', models.CharField(max_length=200)),
                ('specification6', models.CharField(max_length=200)),
            ],
        ),
    ]
