# Generated by Django 5.1.4 on 2025-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(default=1),
        ),
    ]
