# Generated by Django 5.1.4 on 2025-03-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_products_ctry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img5',
        ),
    ]
